"use client";

import { useState } from "react";
import {
  Search,
  Brain,
  AlertTriangle,
  Clock,
  Target,
  Shield,
  ChevronRight,
  Send,
  Sparkles,
  Bot,
  User,
  Copy,
  CheckCircle,
  XCircle,
  Info,
  Server,
} from "lucide-react";
import { investigationResults, aiChatMessages, threatAlerts } from "@/lib/mock-data";

function MarkdownContent({ content }: { content: string }) {
  // Simple markdown renderer for the AI chat
  const lines = content.split("\n");
  return (
    <div className="space-y-2 text-sm leading-relaxed">
      {lines.map((line, i) => {
        if (line.startsWith("## ")) {
          return <h3 key={i} className="text-base font-semibold text-slate-100 mt-3">{line.replace("## ", "")}</h3>;
        }
        if (line.startsWith("### ")) {
          return <h4 key={i} className="text-sm font-semibold text-slate-200 mt-2">{line.replace("### ", "")}</h4>;
        }
        if (line.startsWith("**") && line.endsWith("**")) {
          return <p key={i} className="font-semibold text-slate-200">{line.replace(/\*\*/g, "")}</p>;
        }
        if (line.startsWith("- ")) {
          return <li key={i} className="ml-4 text-slate-300 list-disc">{line.replace("- ", "")}</li>;
        }
        if (line.startsWith("1. ") || line.startsWith("2. ") || line.startsWith("3. ") || line.startsWith("4. ") || line.startsWith("5. ") || line.startsWith("6. ")) {
          return <li key={i} className="ml-4 text-slate-300 list-decimal">{line.replace(/^\d+\.\s/, "")}</li>;
        }
        if (line.startsWith("|")) {
          return <p key={i} className="text-slate-400 font-mono text-xs">{line}</p>;
        }
        if (line.trim() === "") return <br key={i} />;
        return <p key={i} className="text-slate-400">{line}</p>;
      })}
    </div>
  );
}

export default function InvestigationPage() {
  const [selectedInvestigation, setSelectedInvestigation] = useState(investigationResults[0]);
  const [chatInput, setChatInput] = useState("");
  const [messages, setMessages] = useState(aiChatMessages);
  const [isTyping, setIsTyping] = useState(false);

  const handleSend = () => {
    if (!chatInput.trim()) return;
    setMessages([...messages, { role: "user" as const, content: chatInput }]);
    setChatInput("");
    setIsTyping(true);
    setTimeout(() => {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant" as const,
          content: `## Analysis in Progress\n\nI'm analyzing your query: "${chatInput}"\n\n### Preliminary Findings\nBased on the current threat landscape and system telemetry, here's what I've found:\n\n1. 🔍 **Pattern Match**: Query correlates with ${Math.floor(Math.random() * 5 + 2)} known threat patterns\n2. 📊 **Risk Assessment**: Estimated risk level is ${["Medium", "High", "Critical"][Math.floor(Math.random() * 3)]}\n3. ⚡ **Recommended Action**: Further investigation recommended\n\n### Next Steps\n- Review affected system logs\n- Cross-reference with threat intelligence feeds\n- Update incident response plan\n\n*This analysis was generated by RiskLens AI Investigation Engine.*`,
        },
      ]);
      setIsTyping(false);
    }, 2000);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-slate-100">AI Investigation</h1>
        <p className="text-slate-400 mt-1">AI-powered incident investigation and root cause analysis</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Investigation Details */}
        <div className="lg:col-span-2 space-y-6">
          {/* Investigation Selector */}
          <div className="glass rounded-xl p-4">
            <h3 className="text-sm font-medium text-slate-400 mb-3">Active Investigations</h3>
            <div className="flex gap-3">
              {investigationResults.map((inv) => (
                <button
                  key={inv.id}
                  onClick={() => setSelectedInvestigation(inv)}
                  className={`flex-1 p-3 rounded-lg border text-left transition-all ${
                    selectedInvestigation.id === inv.id
                      ? "border-cyan-500/50 bg-cyan-500/5"
                      : "border-slate-700/50 bg-slate-800/30 hover:border-slate-600"
                  }`}
                >
                  <div className="text-sm font-medium text-slate-200">{inv.id}</div>
                  <div className="text-xs text-slate-500 mt-1">Incident {inv.incidentId}</div>
                  <div className="flex items-center gap-2 mt-2">
                    <span className="text-xs text-red-400">Risk: {inv.riskScore}</span>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* AI Summary */}
          <div className="glass rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles size={18} className="text-cyan-400" />
              <h3 className="text-base font-semibold text-slate-100">AI Analysis Summary</h3>
            </div>
            <p className="text-sm text-slate-300 leading-relaxed">{selectedInvestigation.aiSummary}</p>
          </div>

          {/* Root Cause */}
          <div className="glass rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <Target size={18} className="text-orange-400" />
              <h3 className="text-base font-semibold text-slate-100">Root Cause</h3>
            </div>
            <p className="text-sm text-slate-300 leading-relaxed">{selectedInvestigation.rootCause}</p>
          </div>

          {/* Attack Timeline */}
          <div className="glass rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <Clock size={18} className="text-teal-400" />
              <h3 className="text-base font-semibold text-slate-100">Attack Timeline</h3>
            </div>
            <div className="relative">
              <div className="absolute left-[67px] top-0 bottom-0 w-px bg-slate-700/50" />
              <div className="space-y-4">
                {selectedInvestigation.attackTimeline.map((event, i) => {
                  const sevColor = event.severity === 'critical' ? 'bg-red-400 shadow-red-400/50' : event.severity === 'high' ? 'bg-orange-400 shadow-orange-400/50' : event.severity === 'medium' ? 'bg-amber-400 shadow-amber-400/50' : 'bg-green-400 shadow-green-400/50';
                  return (
                    <div key={i} className="flex items-start gap-4 animate-slide-up" style={{ animationDelay: `${i * 0.1}s` }}>
                      <span className="text-xs font-mono text-slate-500 w-[52px] pt-0.5 shrink-0">{event.time}</span>
                      <div className="relative z-10">
                        <div className={`w-3 h-3 rounded-full ${sevColor} shadow-md mt-1`} />
                      </div>
                      <div className="flex-1 pb-2">
                        <p className="text-sm text-slate-200">{event.event}</p>
                        <span className={`inline-block mt-1 px-2 py-0.5 rounded text-xs ${
                          event.severity === 'critical' ? 'bg-red-500/10 text-red-400' :
                          event.severity === 'high' ? 'bg-orange-500/10 text-orange-400' :
                          event.severity === 'medium' ? 'bg-amber-500/10 text-amber-400' :
                          'bg-green-500/10 text-green-400'
                        }`}>
                          {event.severity}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* Affected Assets */}
          <div className="glass rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <Server size={18} className="text-purple-400" />
              <h3 className="text-base font-semibold text-slate-100">Affected Assets</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              {selectedInvestigation.affectedAssets.map((asset) => (
                <span key={asset} className="px-3 py-1.5 bg-slate-800/80 rounded-lg text-xs text-slate-300 font-mono border border-slate-700/50 flex items-center gap-1.5">
                  <Server size={12} className="text-slate-500" />
                  {asset}
                </span>
              ))}
            </div>
          </div>

          {/* Recommendations */}
          <div className="glass rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <Shield size={18} className="text-green-400" />
              <h3 className="text-base font-semibold text-slate-100">Mitigation Recommendations</h3>
            </div>
            <div className="space-y-3">
              {selectedInvestigation.recommendation.map((rec, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-slate-800/30 rounded-lg border border-slate-700/30">
                  <div className="w-6 h-6 bg-cyan-500/10 rounded-full flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-xs text-cyan-400 font-medium">{i + 1}</span>
                  </div>
                  <p className="text-sm text-slate-300">{rec}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right: AI Chat */}
        <div className="lg:col-span-1">
          <div className="glass rounded-xl flex flex-col h-[calc(100vh-180px)] sticky top-6">
            {/* Chat Header */}
            <div className="p-4 border-b border-slate-700/50">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 bg-gradient-to-br from-cyan-500 to-teal-500 rounded-lg flex items-center justify-center">
                  <Brain size={16} className="text-white" />
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-slate-100">AI Security Assistant</h3>
                  <span className="text-xs text-green-400 flex items-center gap-1">
                    <span className="w-1.5 h-1.5 bg-green-400 rounded-full" />
                    Online
                  </span>
                </div>
              </div>
            </div>

            {/* Chat Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {messages.map((msg, i) => (
                <div key={i} className={`flex gap-3 ${msg.role === "user" ? "flex-row-reverse" : ""}`}>
                  <div className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 ${
                    msg.role === "user" ? "bg-slate-700" : "bg-gradient-to-br from-cyan-500 to-teal-500"
                  }`}>
                    {msg.role === "user" ? <User size={14} className="text-slate-300" /> : <Bot size={14} className="text-white" />}
                  </div>
                  <div className={`max-w-[85%] p-3 rounded-xl ${
                    msg.role === "user"
                      ? "bg-cyan-500/10 border border-cyan-500/20 text-slate-200 text-sm"
                      : "bg-slate-800/50 border border-slate-700/50"
                  }`}>
                    {msg.role === "user" ? (
                      <p className="text-sm">{msg.content}</p>
                    ) : (
                      <MarkdownContent content={msg.content} />
                    )}
                  </div>
                </div>
              ))}
              {isTyping && (
                <div className="flex gap-3">
                  <div className="w-7 h-7 rounded-full bg-gradient-to-br from-cyan-500 to-teal-500 flex items-center justify-center shrink-0">
                    <Bot size={14} className="text-white" />
                  </div>
                  <div className="bg-slate-800/50 border border-slate-700/50 px-4 py-3 rounded-xl">
                    <div className="flex gap-1.5">
                      <span className="w-2 h-2 bg-cyan-400 rounded-full animate-bounce" style={{ animationDelay: '0s' }} />
                      <span className="w-2 h-2 bg-cyan-400 rounded-full animate-bounce" style={{ animationDelay: '0.15s' }} />
                      <span className="w-2 h-2 bg-cyan-400 rounded-full animate-bounce" style={{ animationDelay: '0.3s' }} />
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Chat Input */}
            <div className="p-4 border-t border-slate-700/50">
              <div className="flex gap-2">
                <input
                  type="text"
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleSend()}
                  placeholder="Ask about threats..."
                  className="flex-1 bg-slate-800/50 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-200 placeholder-slate-500 outline-none focus:border-cyan-500/50 transition-colors"
                />
                <button
                  onClick={handleSend}
                  className="p-2 bg-gradient-to-r from-cyan-500 to-teal-500 rounded-lg text-white hover:opacity-90 transition-opacity"
                >
                  <Send size={16} />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
